### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Charlie-robin** [Theo-Ross/week1-challenge#1]
# Feedback

## Requirements:

1. A deployed website (using GitHub Pages) : DONE
2. A public GitHub repository for your codebase : DONE
3. Use HTML & SCSS : DONE
4. Make good use of semantic HTML elements :DONE
5. Be responsive (mobile-first) and built with accessibility in mind : DONE
6. Code is highly readable (good naming and indented correctly) : DONE - needs work

## Score

[MARKING-SCHEME](https://github.com/nology-tech/Augusta-Course-Resources/blob/main/student-resources/00-slides/01-web/marking-scheme.md)

| Category             | Score    |
| -------------------- | -------- |
| Site Output          | 30 / 50  |
| Responsiveness       | 10 / 15  |
| Code Knowledge & Use | 10 / 20  |
| Readability          | 10 / 15  |
| Version Control      | 10 / 10  |
| Total Score          | 70 / 110 |

## Positive

As your first project, I think that this is a success, you have clearly enjoyed coding a website from a wireframe and have been able to apply the majority of topics we have learnt. If you ever need a break pick a section from a website and try and recreate it.

The website looks good on mobile and almost matches the design. There are a couple of tweaks you will need to make mainly around the projects section. The circles look a bit off and you will want to hide the react, and scss on mobile and stack them on desktop.

```scss
.portfolio__titles {
  display: flex;
  align-items: center;
  // ^^^ WILL STOP THE WEIRD STRETCH ON THE CIRCLES
}
```

Great use of Git and Github, keep on committing with meaningful messages.

You are demonstrating a solid understanding of the majority of topics we have covered so far, some do need to be refined but that will come with practice. Keep on using the tools we have covered so far going forward!

## Constructive

- You have a `_variables.scss` with no variables in it? SHould be a quick fix to move them from `_base.scss`
- You have 4 `<h1>'s`, you should only have one [w3](https://www.w3schools.com/tags/tag_hn.asp), this would be for the main title of the page. You can use 1 h1 then can use h2 - h6 for other sub headings and titles.
- Your media queries are doing too much. You only need to target the properties that need to change in them. So you do not need the same declarations in both.
  - Below is just an example but you are doing it with a couple of other classes. Less code with CSS is always better.

```scss
.bottom {
  display: flex;
  flex-direction: column;
  align-items: center;

  // OTHER STYLES HERE
}

@media screen and (min-width: 1040px) {
  // OTHER STYLES HERE

  .bottom {
    // THESE HAVE ALREADY BEEN SET YOU DO NOT NEED TO DO IT AGAIN
    // UNLESS THEY CHANGE
    display: flex;
    flex-direction: column;
    align-items: center;
  }
}
```

- Your BEM is a bit hit and miss which is fine as it takes practice.

- You are close with your modifiers, you generally nest them in the class. I will give an example below.

  ```scss
  .skills {
    &__p {
      font-size: 0.9rem;
      margin-left: 5%;
      padding: 2%;
    }

    &__p--icon {
      font-size: 0.9rem;
      margin: 0.3rem;
      display: flex;
      flex-direction: row;
      justify-content: center;
    }
  }

  // WOULD BE

  .skills {
    &__p {
      font-size: 0.9rem;
      margin-left: 5%;
      padding: 2%;

      &--icon {
        display: flex;
        flex-direction: row;
        justify-content: center;
      }
    }
  }
  ```

- The class name should describe what it is, generally, you wouldn't use the tag name in the class. Keep it descriptive. I will give an example below.

```html
<div class="skills">
  <div class="skills__header">
    <h1 class="skills__h1">SKILLS.</h1>
    <p class="skills__p">
      Egestas dictumst enim dui ante nisl risus commodo. Pellentesque dignissim praesent purus in neque erat et. Cras
      donec ut orci eget neque bibendum cras. Vitae, ultricies arcu pretium duis.
    </p>
  </div>

  <div class="skills__icons">
    <div class="skills__iconcon">
      <img src="./images/Vectorgit.jpg" alt="git" class="skills__icon" />
      <p class="skills__p--icon">GitHub</p>
    </div>

    <!-- OTHER HTML SKIPPED TO KEEP IT SHORT -->
  </div>


</div>

<!-- WOULD BE -->
<!-- USE A SECTION  -->
  <section class="skills">
    <div class="skills__header">
      <!-- CHANGE HTML FROM H1 -> H2 -->
      <h2 class="skills__title">SKILLS.</h2>
      <!-- MORE DESCRIPTIVE NAMES -->
      <p class="skills__text">
        Egestas dictumst enim dui ante nisl risus commodo. Pellentesque dignissim praesent purus in neque erat et. Cras
        donec ut orci eget neque bibendum cras. Vitae, ultricies arcu pretium duis.
      </p>
    </div>

    <div class="skills__icons">
      <!-- CAN USE A HYPHEN FOR TWO WORDS -->
      <div class="skills__icon-con">
        <img src="./images/Vectorgit.jpg" alt="git" class="skills__icon" />
        <p class="skills__text skills__text--icon">GitHub</p>
      </div>
    </div>

    <!-- OTHER HTML SKIPPED TO KEEP IT SHORT -->
  </div>
</section>
```

Please take these points further with your next project, use SCSS and the awesome features it gives you. Keep using BEM for naming as well.

Reach out if you do run into any problems.
